on-unmatched = "info"
tree-root-file = "flake.nix"

[formatter.nixfmt]
command = "nixfmt"
includes = [ "*.nix" ]

[formatter.deadnix]
command = "deadnix"
options = [ "--edit", "--no-lambda-arg", "--no-lambda-pattern-names" ]
includes = [ "*.nix" ]

[formatter.keep-sorted]
command = "keep-sorted"
includes = [ "*" ]
